In [1]:
import torch


In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
x = x.reshape(2, 4)
y = torch.tensor([1, 2, 3, 4])
x += y
x

In [ ]:
mat = torch.ones(8, 8)
mat


In [ ]:
mat = torch.triu(mat)
mat

In [ ]:
mat = torch.triu(mat, diagonal=1)
mat

In [ ]:
mask = torch.full((8, 8), float("-inf"))
mask

In [ ]:
mask = torch.triu(mask, diagonal=1)
mask

In [ ]:
masked = mask + mat
masked

In [ ]:
scores = torch.softmax(masked, dim=-1)
scores

In [37]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])


In [38]:
x = x.view(-1, 2, 2)
print(x.shape)
x 

torch.Size([4, 2, 2])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [39]:
x = x.transpose(0, 1)
print(x.shape)
x

torch.Size([2, 4, 2])


tensor([[[1, 2],
         [5, 6],
         [1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8],
         [3, 4],
         [7, 8]]])

In [ ]:
x = x.reshape(2, 2, -1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])