In [2]:
import torch


In [ ]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
x = x.reshape(2, 4)
y = torch.tensor([1, 2, 3, 4])
x += y
x

In [ ]:
mat = torch.ones(8, 8)
mat


In [ ]:
mat = torch.triu(mat)
mat

In [ ]:
mat = torch.triu(mat, diagonal=1)
mat

In [ ]:
mask = torch.full((8, 8), float("-inf"))
mask

In [ ]:
mask = torch.triu(mask, diagonal=1)
mask

In [ ]:
masked = mask + mat
masked

In [ ]:
scores = torch.softmax(masked, dim=-1)
scores

In [37]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])


In [38]:
x = x.view(-1, 2, 2)
print(x.shape)
x 

torch.Size([4, 2, 2])


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [39]:
x = x.transpose(0, 1)
print(x.shape)
x

torch.Size([2, 4, 2])


tensor([[[1, 2],
         [5, 6],
         [1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8],
         [3, 4],
         [7, 8]]])

In [ ]:
x = x.reshape(2, 2, -1)

In [19]:
a = torch.rand(2, 3, 4)
a = a.view(-1, 4)
a = a.transpose(0,1)
print("a:", a)
mask = torch.tensor([True, False, True, False])
b = a[mask]
b

a: tensor([[0.1956, 0.7306, 0.6369, 0.7832, 0.0937, 0.2018],
        [0.6605, 0.4309, 0.7833, 0.5145, 0.3145, 0.4149],
        [0.1410, 0.0714, 0.5312, 0.3424, 0.6954, 0.7581],
        [0.8888, 0.7148, 0.7797, 0.4371, 0.1071, 0.5223]])


tensor([[0.1956, 0.7306, 0.6369, 0.7832, 0.0937, 0.2018],
        [0.1410, 0.0714, 0.5312, 0.3424, 0.6954, 0.7581]])

In [22]:
m = torch.rand(4, 4)
print("m:", m)

# m = m.view(-1)
# m

m = m.repeat_interleave(2, dim=0)
m

m: tensor([[0.3787, 0.1466, 0.1420, 0.6169],
        [0.8996, 0.4731, 0.3694, 0.9113],
        [0.6274, 0.5452, 0.9354, 0.2560],
        [0.3961, 0.9913, 0.1662, 0.1036]])


tensor([[0.3787, 0.1466, 0.1420, 0.6169],
        [0.3787, 0.1466, 0.1420, 0.6169],
        [0.8996, 0.4731, 0.3694, 0.9113],
        [0.8996, 0.4731, 0.3694, 0.9113],
        [0.6274, 0.5452, 0.9354, 0.2560],
        [0.6274, 0.5452, 0.9354, 0.2560],
        [0.3961, 0.9913, 0.1662, 0.1036],
        [0.3961, 0.9913, 0.1662, 0.1036]])